name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  buildC:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: | 
          cd srcC/
          docker build . --file Dockerfile --tag dipugodocker/test-c:1.0

      - name: run container
        run: docker run dipugodocker/test-c:1.0

      - name: push image
        env:
          SUPER_PASS: ${{ secrets.DOCKER_PASS }}
          SUPER_USR: ${{ secrets.DOCKER_USR }}
        run: |
          docker login -u "$SUPER_USR" -p "$SUPER_PASS"
          docker push dipugodocker/test-c:1.0
      

  buildGo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: | 
          cd srcgo/
          docker build . --file Dockerfile --tag dipugodocker/test-go:1.0

      - name: run container
        run: docker run dipugodocker/test-go:1.0
      
      - name: push image
        env:
          SUPER_PASS: ${{ secrets.DOCKER_PASS }}
          SUPER_USR: ${{ secrets.DOCKER_USR }}
        run: |
          docker login -u "$SUPER_USR" -p "$SUPER_PASS"
          docker push dipugodocker/test-go:1.0
